# STAGE 1: Сборка React-приложения
FROM node:18-alpine AS builder

WORKDIR /app
COPY style-transfer-frontend/package*.json ./
RUN npm ci --silent

COPY style-transfer-frontend .
RUN npm run build

# STAGE 2: Продакшен-сервер через nginx
FROM nginx:stable-alpine

# Копируем собранный React-код
COPY --from=builder /app/build /usr/share/nginx/html

# Копируем конфигурацию nginx (создадим её дальше)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]